// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/02       [394754]
Creator        : bcarls
Date           : Mon Mar 28 10:41:55 2016
Host           : Darwin elcapitanvm.local 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64
Dir            : /Users/bcarls/anatreeloop/MVACosmic
Training events: 8000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 5
trackPerpDistToABound         trackPerpDistToABound         trackPerpDistToABound         trackPerpDistToABound         cm                                'F'    [0.00113770668395,115.051826477]
trackPIDA                     trackPIDA                     trackPIDA                     trackPIDA                     stuff                             'F'    [0,99.3015975952]
log(trackRange)               log_trackRange_               log(trackRange)               log(trackRange)                                                 'F'    [-1.05606532097,13.9381923676]
trackThetaYZ                  trackThetaYZ                  trackThetaYZ                  trackThetaYZ                  radians                           'F'    [0.000496195920277,1.57066810131]
trackNearestDistUntaggedToTaggedCosGT trackNearestDistUntaggedToTaggedCosGT trackNearestDistUntaggedToTaggedCosGT trackNearestDistUntaggedToTaggedCosGT cm                                        'F'    [8.27170952107e-05,496.195098877]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 5 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "trackPerpDistToABound", "trackPIDA", "log(trackRange)", "trackThetaYZ", "trackNearestDistUntaggedToTaggedCosGT" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][5];
   double fMax_1[3][5];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[5];
   double fVmax[5];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[5];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[11][6];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][11];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 6; fWeights[0] = new double[6]; 
   fLayerSize[1] = 11; fWeights[1] = new double[11]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.865556387429233;
   fWeightMatrix0to1[1][0] = 2.12803440653141;
   fWeightMatrix0to1[2][0] = 2.09457196525254;
   fWeightMatrix0to1[3][0] = -0.0578123862202267;
   fWeightMatrix0to1[4][0] = -7.43486506590194;
   fWeightMatrix0to1[5][0] = 0.0524398310119195;
   fWeightMatrix0to1[6][0] = -1.07017374947364;
   fWeightMatrix0to1[7][0] = 0.766330764063865;
   fWeightMatrix0to1[8][0] = -1.91876429506875;
   fWeightMatrix0to1[9][0] = -0.855784164133924;
   fWeightMatrix0to1[0][1] = -2.43252769035248;
   fWeightMatrix0to1[1][1] = 0.045636871942386;
   fWeightMatrix0to1[2][1] = -1.25243849212201;
   fWeightMatrix0to1[3][1] = 6.00717362755574;
   fWeightMatrix0to1[4][1] = 0.331043654667253;
   fWeightMatrix0to1[5][1] = 0.100439969793451;
   fWeightMatrix0to1[6][1] = 1.75669026455134;
   fWeightMatrix0to1[7][1] = 2.28649812216804;
   fWeightMatrix0to1[8][1] = -0.164483732678523;
   fWeightMatrix0to1[9][1] = 1.83948614163362;
   fWeightMatrix0to1[0][2] = 0.337368783487713;
   fWeightMatrix0to1[1][2] = -0.93943447438696;
   fWeightMatrix0to1[2][2] = -0.847088517370205;
   fWeightMatrix0to1[3][2] = 2.76194507094879;
   fWeightMatrix0to1[4][2] = -0.0804806486922609;
   fWeightMatrix0to1[5][2] = -0.809776103615156;
   fWeightMatrix0to1[6][2] = 2.70278441038117;
   fWeightMatrix0to1[7][2] = -1.29457924719612;
   fWeightMatrix0to1[8][2] = -3.8702045013074;
   fWeightMatrix0to1[9][2] = 3.48913611702632;
   fWeightMatrix0to1[0][3] = 3.31515576673079;
   fWeightMatrix0to1[1][3] = 1.07458257383395;
   fWeightMatrix0to1[2][3] = -1.26849418175797;
   fWeightMatrix0to1[3][3] = 0.252417102002776;
   fWeightMatrix0to1[4][3] = -0.0487075571863362;
   fWeightMatrix0to1[5][3] = -0.171061322607379;
   fWeightMatrix0to1[6][3] = -2.25003332426402;
   fWeightMatrix0to1[7][3] = 2.5686161456866;
   fWeightMatrix0to1[8][3] = -0.766951971044251;
   fWeightMatrix0to1[9][3] = 0.823970961215872;
   fWeightMatrix0to1[0][4] = 1.38121424008997;
   fWeightMatrix0to1[1][4] = 1.48700930181717;
   fWeightMatrix0to1[2][4] = 1.80485651507212;
   fWeightMatrix0to1[3][4] = 0.105183044539064;
   fWeightMatrix0to1[4][4] = 0.399882877893113;
   fWeightMatrix0to1[5][4] = -7.33319294109305;
   fWeightMatrix0to1[6][4] = 1.62829098051565;
   fWeightMatrix0to1[7][4] = -0.50655349010971;
   fWeightMatrix0to1[8][4] = 1.76973517943687;
   fWeightMatrix0to1[9][4] = 0.0780037999905996;
   fWeightMatrix0to1[0][5] = -0.924043611846844;
   fWeightMatrix0to1[1][5] = 0.600905162734094;
   fWeightMatrix0to1[2][5] = -0.788760185373991;
   fWeightMatrix0to1[3][5] = 6.84654311522366;
   fWeightMatrix0to1[4][5] = -7.14186684304119;
   fWeightMatrix0to1[5][5] = -7.44745827675461;
   fWeightMatrix0to1[6][5] = -0.347692432669195;
   fWeightMatrix0to1[7][5] = -2.46136550011852;
   fWeightMatrix0to1[8][5] = 0.272207763691694;
   fWeightMatrix0to1[9][5] = 0.824477665997404;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.883236501344954;
   fWeightMatrix1to2[0][1] = 0.543723354457231;
   fWeightMatrix1to2[0][2] = 0.634119685978618;
   fWeightMatrix1to2[0][3] = 2.91752130448081;
   fWeightMatrix1to2[0][4] = 3.54234426445921;
   fWeightMatrix1to2[0][5] = -2.55435014484812;
   fWeightMatrix1to2[0][6] = 1.96456527418478;
   fWeightMatrix1to2[0][7] = 1.82668641208445;
   fWeightMatrix1to2[0][8] = 1.0964680450376;
   fWeightMatrix1to2[0][9] = -2.42227522388482;
   fWeightMatrix1to2[0][10] = 0.755512372186963;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.00221298402175;
   fMax_1[0][0] = 110.455490112;
   fMin_1[1][0] = 0.00113770668395;
   fMax_1[1][0] = 115.051826477;
   fMin_1[2][0] = 0.00113770668395;
   fMax_1[2][0] = 115.051826477;
   fMin_1[0][1] = 0;
   fMax_1[0][1] = 99.3015975952;
   fMin_1[1][1] = 0;
   fMax_1[1][1] = 97.6245117188;
   fMin_1[2][1] = 0;
   fMax_1[2][1] = 99.3015975952;
   fMin_1[0][2] = -0.946228861809;
   fMax_1[0][2] = 9.34540271759;
   fMin_1[1][2] = -1.05606532097;
   fMax_1[1][2] = 13.9381923676;
   fMin_1[2][2] = -1.05606532097;
   fMax_1[2][2] = 13.9381923676;
   fMin_1[0][3] = 0.00175228912849;
   fMax_1[0][3] = 1.57018554211;
   fMin_1[1][3] = 0.000496195920277;
   fMax_1[1][3] = 1.57066810131;
   fMin_1[2][3] = 0.000496195920277;
   fMax_1[2][3] = 1.57066810131;
   fMin_1[0][4] = 0.00242687016726;
   fMax_1[0][4] = 496.195098877;
   fMin_1[1][4] = 8.27170952107e-05;
   fMax_1[1][4] = 365.335418701;
   fMin_1[2][4] = 8.27170952107e-05;
   fMax_1[2][4] = 496.195098877;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 5;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<5;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
